bind 0.0.0.0
port 26379
sentinel monitor mymaster redis-sentinel-master 6379 2
sentinel down-after-milliseconds mymaster 3000
sentinel failover-timeout mymaster 10000
sentinel parallel-syncs mymaster 1
